const DB_ID = process.env.APPWRITE_DB_ID || "";
const DENTISTS_COLLECTION = process.env.APPWRITE_DENTISTS_COLLECTION || "";
const APPOINTMENTS_COLLECTION =
  process.env.APPWRITE_APPOINTMENTS_COLLECTION || "";
const USERS_COLLECTION = process.env.APPWRITE_USERS_COLLECTION || "";

export {
  DB_ID,
  DENTISTS_COLLECTION,
  APPOINTMENTS_COLLECTION,
  USERS_COLLECTION,
};
